---
- name: Install dependencies 
  become: yes
  hosts: webservers
  vars: 
    dependencies:
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-setuptools
      - python3-setuptools
      - python3-venv
    

  tasks:

    - name: Install requried packages on Debian-based server
      ansible.builtin.apt: 
        pkg: "{{ dependencies }}"
        state: present
        update_cache: yes