packages:
  - python3-pip
  - python3-dev
  - build-essential
  - libssl-dev
  - libffi-dev
  - python-setuptools
  - python3-setuptools
  - python3-venv
  - python-cryptography
  - nginx
python_libs:
  - wheel
  - uwsgi
  - flask
  - emoji
server_ipv4: 192.168.1.102  
service_user_name: emoji_service
service_user_password: $6$2Dzz2hF3t$icC9YKy2KBy5DBcyO/oKOmoRtoaD1o0snbCJMjWz7xWWCp0K/.3SYIrdfMSoA7SIf53ZvP8NAtYNRzn4XrZXC/
service_user_home: "/home/{{ service_user_name }}"
