
Vagrant.configure("2") do |config|

  config.vm.define "emojiService" do | emojiService |

    config.vm.box = "debian/contrib-buster64"

  # Disable VirtualBox Guest Additions check because this box already has it.
    if Vagrant.has_plugin?("vagrant-vbguest") then
          config.vbguest.auto_update = false
    end

    # VM Provider settings
    config.vm.provider "virtualbox" do |v|
      v.name = "emojiService"
      v.memory = 2048
      v.cpus = 2
    end

    config.vm.hostname = "emoji-service"
    config.vm.network "private_network", ip: "192.168.1.102"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder "emoji-py/", "/home/vagrant/emoji-py", 
    owner: "vagrant", group: "vagrant"

  end

end