
Vagrant.configure("2") do |config|

  config.vm.define "service" do | service |

    config.vm.box = "debian/contrib-buster64"

  # Disable VirtualBox Guest Additions check because this box already has it.
    if Vagrant.has_plugin?("vagrant-vbguest") then
          config.vbguest.auto_update = false
    end

    # VM Provider settings
    config.vm.provider "virtualbox" do |v|
      v.name = "service"
      v.memory = 2048
      v.cpus = 2
    end

    config.vm.hostname = "service"
    config.vm.network "private_network", ip: "192.168.1.102"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 8443
    config.vm.synced_folder "emoji-py/", "/home/vagrant/emoji-py", 
    owner: "vagrant", group: "vagrant"

    # Run Ansible provisioner to deploy the emoji-service
    config.vm.provision "deploy-emoji-service", type:'ansible' do |ansible|
        ansible.verbose = "vv"
        #ansible.inventory_path = 'ansible_provision/hosts.yaml'
        ansible.playbook = "ansible_provision/deploy.yml"  
    end

  end

end