all:
  children:
    web_services:
      hosts:
        service: 
          ansible_host: 192.168.1.102
          ansible_user: vagrant
          #ansible_ssh_private_key_file: /home/vkutas/andersen/home task 1/task4/.vagrant/machines/service/virtualbox/private_key